<?php
$sql_connection = new mysqli("localhost","root","","rearing");

$sql_connection->query("CREATE TABLE IF NOT EXISTS subcounty(ID INT(11) NOT NULL AUTO_INCREMENT, PRIMARY KEY(ID), NAME VARCHAR(30) NOT NULL UNIQUE)");


$sql_connection->query("CREATE TABLE IF NOT EXISTS members(ID INT(11) NOT NULL AUTO_INCREMENT, PRIMARY KEY(ID), NAME VARCHAR(30) NOT NULL, SUBCOUNTY_ID INT(11) NOT NULL, PHONE_NUMBER VARCHAR(20) NOT NULL UNIQUE, PASSWORD VARCHAR(100) NOT NULL, EMAIL_ADDRESS VARCHAR(30) NOT NULL UNIQUE, FOREIGN KEY(SUBCOUNTY_ID) REFERENCES subcounty(ID) )");
